language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
script: "bundle exec rake"
gemfile:
  - Gemfile
before_install:
  - uname -a
  - sudo apt-get install libexif-dev libjpeg8-dev
  - gem -v
  - gem install bundler -v '~> 1.7'
